
spring:
  application:
    name: springboot-crud-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

  security:
    user:
      name: user
      password: user
      roles: ADMIN


